### ISSUE TITLE
Felling axes not counted

### ISSUE THREAD

**Issue by TheAssailant** [Infinitay/tree-count-plugin#22]
Loving this plugin to maximize the Forestry bonus I get, but it seems it does not currently track felling axes interacting with the trees. Any news on when this might get fixed?

**Comment by Infinitay** [comment]
I've been meaning to get this fixed but I currently don't have membership to test the changes. It's as simple as adding in the new axe data, but I would like to test it and confirm everything is working. I'll see what I can do.

**Comment by TheAssailant** [comment]
No rush, not a huge deal, just wanted to make the issue so anyone else wondering the same knows its being worked on.

**Comment by Infinitay** [comment]
I have submitted the update. I'll leave the issue open until the folks at RuneLite accept the changes and push the update to the Plugin Hub.

https://github.com/runelite/plugin-hub/pull/5136
